dist: xenial

script:
- src/scripts/package v02
- bash -c "cd release && zip -9 -r win64.zip win64"
- bash -c "cd release && zip -9 -r macos.zip macos"

deploy:
  provider: releases
  file_glob: true
  file: release/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: false
  user: "kdridi"
  password:
    secure: v3XfWfWSl56Yidl4gY6JjEz1/N+VGPawYB54LgIfWTc7g/tkZoskclf/pQ///RrWVs0hlUS9tzC8sfWs3XyMfIc5rnvXhM7XxX9sXb6U5QjobPfP+6gsEOQr9nFrvpTkYQnURmatzyWu4S+VrUuGdt7/6g5kCJJ15FY93vvrx3/Ik4w82Yv6PRCsMRiIJq3Tq00SNqBz2zGlrS9adlYIeghG3JMBwEAhTHHrMM5ZbDBQFtU7KzlMRLqNYIS/vplYEh1ZT68NTdd0rSNeWldfv1YUSKfdyRoVUMIx+RYZk4oK4su0f9du9N2sRflQvbbM71REhiD/1vJy/KEqACsSysVnYl8rqzLpeq0lfq1dTkTs+Sh3iGsHfUgfdLLssvxSj6BoYSF/7KaJKflP05YJ3oymYel7FXCLEVcG8HfVChl7x7SxJgkgGBggl/2N4OrtJmDpZdKpWqGGk0yzqJ7xRPyBQa3ch3jvDPTufDcZwG51dXlnD5I3URK+Dk6/UyBPSykboRe/4Q6O9d1X6eOrnl7vBkY7VGi7SZQp2jWZkcLX3SmZ2KFGbxFb723F5ZtmqzXdk/GaTwf9zpUmzXDSIFBZ3jFdyUV8Fyi3Oabr+57oNx8UtlspOJVKnhWdVxxjJwsRAez72CWrMH1IidQkdI38uroCx5Yal6IbfImw6XU=
