dist: xenial

script:
- src/scripts/package v02
- bash -c "cd release && zip -9 -r win64.zip win64"
- bash -c "cd release && zip -9 -r macos.zip macos"

deploy:
  provider: releases
  file: release/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: false
  api_key:
    secure: UyZIEFIA6AuXaULareriP/gEsS18PPUFB6tAbqq4+XGX1QXvj5nAJjnWptRzxKv3GYOEAmY2UQtVT/KiRjdUso6sz/0AiorQsCVcCvqWdJhc2FuTNl7InrvPv/wPePs2x/2TK/fPEkIpGkfRTztqDAdaC3vD7vj/pEeZrrg7Xr3iTpxyM5AMQPr6DUp7V/nEhlOypJ9WIrI4CT0r2U9/LvhEiOTJFLf7P5Xj5pqk5KTdJmuU0+FIpXNjcudFAopAVFeWjytyzqPNMQebXMqsJA8Tcd0/P9NBtGIsHxXFUQJEFDgg+7aNGg0t3+R2lKcoDSD4e9EbK/Mijf9tPrIIVRbiofahIj1gwkQ+93rODhniFOTrgembp369aYCf82AcKWIGMdPTh4B7OdI6EwTRMWLuIuhsa9URHAiCFT84BWIcdD2gU/Mm4mX/JUjng3o5CzKSVNr/hiluV5NJOu62lGtdEAdUyLVgzBK5jOpwc5nkzP+1lN+45RE9chLovfYs2Q6WHbwwOd1cqwSXEd3c4IPMcaYdVTKc2ygnYzdTaDkyYEuw1FaT4Bn6j1HqgGSmAWMgRuG/3hHmtdlr0jBaWFODmKQAHiwdoKITves8n3IYC6lZ516XKRUoHG6YtiWWObzhQD17YyJaxNstAD+gdRqdm0L3VP6FIbsmgY4Eg2s=
