dist: xenial

script:
- src/scripts/package v02
- bash -c "cd release && zip -9 -r win64.zip win64"
- bash -c "cd release && zip -9 -r macos.zip macos"

deploy:
  provider: releases
  file_glob: true
  file: release/*.zip
  skip_cleanup: true
  draft: true
  on:
    repo: kdridi/GGJ2019
    tags: false
  api_key:
    secure: JGBVCvXiIjF8YT3gxIa+QX8ma3dFcT3A6ah8z6HNtFBhS5XDuj16p7rFrQMEZmyYlPF5dajCOs3PV2HJq4TPjj7MUL7T7yLPO6AC6xsypgW14sz+/mggbvOo1AWcklYTDWn3TaVSr8M2uCKf/M3Nsbuje/i9gysDpHEoL5I61djQjUTwkONxomBkPjattCXAiHJcVdwcAVj/BgeHQhjcXGZ/pzFNWQy/vXuVA4RfyZZqKLW+imPNpHm+KPSj+/RTlIZLLMfByYYBxP+W5Z42KBRgxhsQhu+cQ/JfhDh3yXYlNfHdT+n0fp1axbk1Z2BN4mEOngR2A4OfwaB0ke43XkyreK8wv8J8O4/9/GiGH3+1hYlbvPvpBgzO/eslyWrruAJY3ePttotBgdu3isXylQyt6gKeeCF+u/83FOn3nVlX99cNZ8A0IXXVER3CV1b+jtewL73UlvV1BSNgJuRkI7rTwRDPC9ZF2hckvtBT1n715+Vcz8JqswXM4B6QuqznQzwZOVRaScbt7Ubiw8ztHwDGObc+0XlksYaMYPnNm2USsDk45Pp8S7iwrwau4duzNKIMHABHVQOeLDz9qCnFuzT/8E5BgxVbeRFNjmQYdabozRkj299Sh8eqm0ZtU0WJRjwJyZXGXkOLuyUV/qfNGx8Dm/KAKfeWATba/Kh6Q14=
