dist: xenial

script:
- src/scripts/package v02
- bash -c "cd release && zip -9 -r win64.zip win64"
- bash -c "cd release && zip -9 -r macos.zip macos"

deploy:
  provider: releases
  file_glob: true
  file: release/*.zip
  skip_cleanup: true
  draft: true
  on:
    tags: false
  user:
    secure: MFo22JJE+VBwy3/RTtLLCnq0ha/90TBm6uIkgHOvQoB1J2iydyKXq68DjdODh2ZphRMHyBaCOX3Z7rZ3n1djC323AyNRL9/euPmv6h7g7FGi2iQYrqYiaFI4wxvgfPvpShPgcf+M72e/4sTFQH7J0q8PR3LFz7a3580ps8yckoeK0il0mQF43q072enWq+1psYzJTzpNyGwPSSex9R3NJJ4+780uvtJ38nZ1r9NndPEof0fCiwLw7VrqlouFpfYEo+k0DhfAumytzXly0nO5ALI40+z9mKgTqTQvNNX1C9xrvSOtf6mcW3udtqrevqWGJBF+GesYhDemouBl53Jc07ayNIf8JNyoiRzTHVfxM2IFjgiG5nmCVwJG74SRR1ZoFheqTuzXcEPLYl6qJrU0Lqfpl29PotIA6FznlSXfl4g0kCPa3vME9I2biCZF+6hfslsfBdcdpiIkowlxxmd1aWNEiOsQPAtOt2nG0zgwp6rJVEo8EM06E4fGs6jCHCdYhc1wrbgQmcDZpfKedEI5CLYh4HHKVjEJbmiG8OdJt8sj3Wor/LttvNRYQrkC5P8PhleNtVc84YN+sYKsb9s/rbJex/9JYs0HXihQCqWKZRoqYho3sLZZLM2laLZU3toTyoQT1d/qdUctDdESZr6OcGhHWdAk93i45vZj2FEhv9Y=
  password:
    secure: ehtIE2qG0iv6r1hjVQyXPArZG9dGdNizMjcdBFvASvr47p8WUI66htDVcrfd3abJYaLxOmeOLnZbp7LlTHLSG9aaMPVDhyQs2If6TLKXtmXrOyoYfsCXBM4QqyfPUJBHd5Zc8g0BW7vgel3BZVdeujNenAeoTU94FzMrK2B5vwV46brb1GGZZD0RSxd0Eu0Z6vSn6TcPJe4ScMcdjhXWZdxj9ujD39MgEsvuwcEvpt+0n3Q8xQ5Cfy2F5t6BiID2E4emWT5tUgM5RBQbtnjHMNXo4nxf/ZO3CdBcbel3wtS5snzR6++q5JoIjTfePSY6Rmojn+ikuPXnoAk5A3liOWQoKLhODw6Y6VAg5FPNMmb9qSdtUYOTWnD2IX54WqBoM93LRFCoFEIzVcrdJZ+Nal0J4cFL4/Vp5W2aD350vo4dI2pLBiBtRrxjegBCLCbmTduG1yfz3XRNGibYrG7n/kxBHauVcYNj+5SRlVig+yoH3LXCZ2Z40BXTscs0SKQ8P1pZ1ioLpwmyYgGrGW42cz0DDk+46efjRWrs7TTaKoK6A/UyVaqm8MOpwSZQWMk3wlyqjr+AgSm06aAd3grBj0l5GEqlgSVzxlx9vB7LNJsHbgoQ0l6n4OsjnLe+28oqjEGp0weFma6kMHkldHEIcO8/HEHYjY5I+TdCDcTjzPk=
