dist: xenial

script:
- src/scripts/package v02
- bash -c "cd release && zip -9 -r win64.zip win64"
- bash -c "cd release && zip -9 -r macos.zip macos"

deploy:
  provider: releases
  file_glob: true
  file: release/*.zip
  skip_cleanup: true
  draft: true
  on:
    repo: kdridi/GGJ2019
    tags: false
  api_key:
    secure: Jp6jb+ZpIZMTyyhu0HgTCri/3ZkV0aXUTIOZ5oYyalHIoeLBQoXUUp54osKDMY+JFMFnFLbzCc+4xCJ315XNkI/7HDdRUFhCGSHCv5IyLpbDb1toFQCejMC/pTRIgxRWh/i3kZqGhhVP/4VAatr7oLdjZV1/aJETd9OEgRbrx/rMZEhK6Suu3UOEPLEjk9Np3L3gMBfpu2duzwqiKESiLbt8zBP9CasnJ+Z+lC9Qra+wxM6tUS5y7CcpJbzUwujzzcAskP5CWu751eyaElvWiEUPGlr49YsRLV2nyWHA2/iKrtYMmjXtvFoMil9hXd6IEyAlrzIzBWa0+1WVV+ljx47jFdlOev0soFpNT2ZauO+Sj6zhKNjtPXe7KBfGZxfFHLJ9nmoVZ9u4TDfj1khvCqRbDJb6UW5drk7074Jx3edPKzsXMYNPV2GGEtf10UaGxfN0plUr1LBrXWCK6Qgmna4I5jzcI1e+pSXPgmUIqvhRhGJuB4a22CLxNG1j3ffwtC6lf3sRP/KG2GtGR4i7psP/QjiM30g/YtyhQR9tNwOSz1xTHunsC/RTBp2Y/pfdWol0FQoQ0Xyy3zvMqKKNeBMzhQtrPAAUw1qs+ecaC0do2h6ibaVSf3Mv8Ia4xLkYgKn3T8qw2eMpXdE7kPR/wSUAJtkjaGTbrWR9ms4khTU=
