dist: xenial

script:
- src/scripts/package v02
- bash -c "cd release && zip -9 -r win64.zip win64"
- bash -c "cd release && zip -9 -r macos.zip macos"

deploy:
  provider: releases
  file: release/*.zip
  skip_cleanup: true
  draft: true
  api_key:
    secure: EYInqL0cODl67SEUj8FK9iSjPd3xQArggjsRw1lF2RASfQWyTgVwUxmHaCkJy5sPmV/52jlZnNAIpf4+oXZ8EmfZoTm082/vwM5snUsMEv254ElWONoZuKimdqxf6rPuX7ai7IYcjCJTYaVYkUbsiJCscpOTmsmzTFU8Cw7+9uDi40yMaJsMmOQFoO741jonVtIFKdNuHGIMaWSkDY4pmyIeP7JFiH4SxGa8iyJwXtfN1v0jSFUk91SQyiZG1sxfqUSr8yEpROhnyWQRdQpSCzzsLVIs3QlBGw8ewG9NWlZiZ20gyXvg1xYiN9IksKClZQJ2AT/KCDSG+TnfBMXJzoZu2/8TKXECikjhQ44ttl5SLZxKzD1txIzROw3p49FxCkDu3Hmnky/TZeEsIS4/1OOF20KG5yn44AV2tY3KnHzE+FQ7LvWu9eehIxNSYx7T8uJoMDCuslaDTVdo3FYOtuwF/XETIkLIKonGc76MUuLmdFkOagM44tLztSHvULr7/qdLdCoPTuYGADTtzv0rQEKwiRqMCOVir7cd5PD/iCCi+VJLSjN/Xdfur7XPuk5qtf9nUJ7j+dM/wej+3tEVk+gocBYnBmQbHdouqSDR9h/L40Uop1m+Gz/4SqwhnomelBv4tK++R36Om+vcDM9VYyONqn4qbRN+ilEK/sDUWIk=
  on:
    tags: false